spring:
  datasource:
    url: jdbc:mysql://parayo-db-dev.cijaf6gurtoh.ap-northeast-2.rds.amazonaws.com/parayo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    username: admin
    password: rkdwjd37
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 엔티티에 변화가 생겼을 때 테이블 스키마도 업데이트한다
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect